### ISSUE TITLE
"Suitable constructor not found" on Asp.net core 2.1

### ISSUE THREAD

**Issue by stjns** [e5enrico/CoreWebApp#1]
@e5enrico I've been banging my head on the desk for two days trying to fix the problem you described here, so thanks for your work on this. I have made all the relevant changes in my project, but I'm getting an error saying it can't find a suitable constructor for the "AuthenticationMiddleware" type when the app is attempting to start (using asp.net core 2.1). 

Any ideas? 

```
System.InvalidOperationException: A suitable constructor for type 'GntyAPI.AuthenticationMiddleware' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor.
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass4_0.<UseMiddleware>b__0(RequestDelegate next)
   at Microsoft.AspNetCore.Builder.Internal.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
```

**Comment by stjns** [comment]
It must be a difference in the way that middleware is implemented in later versions of asp.net core. I picked from your code and got this to work by adding the following as the first middleware in my `startup.cs`: 

```
app.Use(async (context, next) =>
{
  if(context.Request.Method != "OPTIONS" && !context.User.Identity.IsAuthenticated)
  {
    context.Response.StatusCode = 401;
    await context.Response.WriteAsync("Not Authenticated");
  }
  await next.Invoke();
});
```

**Comment by fizch** [comment]
I just came across this and spent several hours researching it. I am using .net core 3.1.

I found the information I needed in this document. [https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/write?view=aspnetcore-3.1](url)

My class ended up looking like this:
```    
    public class AuthenticationMiddleware {
        #region attributes
        private readonly RequestDelegate _next;
        #endregion

        #region ctor
        public AuthenticationMiddleware(RequestDelegate next) {
            _next = next;
        }
        #endregion

        #region method
        private async void BeginInvoke(HttpContext context) {
            //This is to mitigate bug in Chrome - http://stackoverflow.com/questions/15734031/why-does-the-preflight-options-request-of-an-authenticated-cors-request-work-in
            //See also https://github.com/aspnet/CORS/issues/60
            if (context.Request.Method != "OPTIONS" &&
                !context.User.Identity.IsAuthenticated) {
                context.Response.StatusCode = 401;
                await context.Response.WriteAsync("Not Authenticated");
            }
        }

        public async Task Invoke(HttpContext context) {
            this.BeginInvoke(context);
            await this._next.Invoke(context);
        }
        #endregion
    }
```
